upd styles.css hero.html
ultra-marina/project-july2023 pull request #16
Opened 2023-07-30 19:36 UTC by AlinaKalen

2023-07-30 20:27 UTC, ultra-marina requested changes

2023-07-30 20:27 UTC, ultra-marina commented on src/css/hero.css
>      padding-top: 40px;
Верхні падинги можуть знадобитися: в загальних стилях - лише нижні, бо однакові.

2023-07-30 21:07 UTC, AlinaKalen commented on src/css/hero.css
>      padding-top: 40px;
повернула падінги, та прибрала крапку з адресою до картинок

2023-07-31 06:41 UTC, ultra-marina approved these changes

2023-07-31 06:41 UTC, merged