1
ultra-marina/project-july2023 pull request #26
Opened 2023-07-31 14:56 UTC by YAKUDZA1312

Модальне вікно але без скріпта

2023-07-31 20:32 UTC, ultra-marina requested changes
Я почекаю, поки додаси весь код. Бо зараз виглядає так, що це модальне вікно просто стирчатиме посеред сторінки.

2023-07-31 20:32 UTC, ultra-marina commented on src/img/icons.svg
> +     <symbol id="rent-x" viewBox="0 0 32 32">
І стрілку, і хрестик правильніше додати без кольору, а колір задати в css (кольори називати нашими змінними).
Я б також попросила назвати хрестик нейтрально (close-x), щоб його можна було використовувати багаторазово.

2023-08-01 10:08 UTC, YAKUDZA1312 commented on src/partials/rent.html
> +  <div class="rent-modal-div">
воно по іншому працювати не буде принаймні в мене по іншому не виходить

2023-08-01 10:10 UTC, YAKUDZA1312 commented on src/img/icons.svg
> +     <symbol id="rent-x" viewBox="0 0 32 32">
так ви і ментора  казали щоб всі назви класи тощо були унікальними тимпаче моя іконка не використовується кимось іншим

2023-08-01 10:14 UTC, YAKUDZA1312 commented on src/partials/rent.html
> +  <div class="rent-modal-div">
видалив

2023-08-01 10:17 UTC, YAKUDZA1312 commented on src/img/icons.svg
> +     <symbol id="rent-x" viewBox="0 0 32 32">
виправив

2023-08-01 10:54 UTC, ultra-marina approved these changes

2023-08-01 10:54 UTC, merged