1
ultra-marina/project-july2023 pull request #3
Opened 2023-07-29 07:30 UTC by YAKUDZA1312

2023-07-29 12:17 UTC, ultra-marina requested changes

2023-07-29 12:17 UTC, ultra-marina commented on src/css/rent.css
>  .rent-container {
styles.css містить деякі загальні стилі, ми додали туди й дещо про секції та контейнери. Подивіться, будь ласка. Звісно, якщо є заперечення або пропозиції, дайте знати.

2023-07-29 12:29 UTC, YAKUDZA1312 commented on src/css/rent.css
>  .rent-container {
Привіт все чудово) на конференцію не потрапив із-за роботи.Хотів спитати чи є якийсь додаток котрий зменьшує вміст svg.Та куди додавати свою svg та img

2023-07-29 14:11 UTC, ultra-marina commented on src/css/rent.css
>  .rent-container {
Для зображень своєї секції треба створити папку з такою самою назвою в каталозі img (тобто папка img вже існує, а в ній треба створити папку rent і наповнити файлами зображень, які використовуватимуться в секції). Зображення треба обробляти https://squoosh.app/ або подібним чином. Необхідно додати зображення всіх потрібних розмірів, в т.ч. для ретинізованих екранів.
Svg, мабуть, можна класти туди ж, якщо вона не додається до спрайту з якихось причин. Я для svg використовувала лише https://icomoon.io/ та https://jakearchibald.github.io/svgomg/, інших не знаю.

2023-07-29 17:59 UTC, ultra-marina requested changes

2023-07-29 17:59 UTC, ultra-marina commented on src/partials/rent.html
> +          <use href="../img/rent.img/symbol-defs.svg#arrow"></use>
Треба додати стрілку до спільного спрайту. Не варто створювати спрайт на кожну секцію.

2023-07-29 17:59 UTC, ultra-marina commented on src/img/rent.img/symbol-defs.svg
Будь ласка, назвіть папку rent (вона вже знаходиться в каталозі img, нема потреби повторювати це буквосполучення), покладіть до неї фото з яхтою, а svg стрілочки додайте до спільного спрайта.

2023-07-29 17:59 UTC, ultra-marina commented on src/img/rent.img/imgyaht1.jpg
Ви впевнені щодо jpg? Як реалізуєте фігурну форму зображення?
P.S. Будь ласка, назвіть папку rent (вона вже знаходиться в каталозі img, нема потреби повторювати це буквосполучення), а це зображення - rent-yacht-main, наприклад (а картинку яхти для модального вікна - скажімо, rent-yacht-modal).

2023-07-29 17:59 UTC, ultra-marina commented on src/css/rent.css
>  .rent-input-div {
Поясніть, будь ласка, який ефект має бути від цього.

2023-07-29 17:59 UTC, ultra-marina commented on src/css/rent.css
> +background-color: black;
Це тимчасове рішення?

2023-07-30 18:42 UTC, ultra-marina approved these changes

2023-07-30 18:43 UTC, merged

2023-07-30 18:45 UTC, YAKUDZA1312 commented on src/img/rent.img/symbol-defs.svg
Добре,зробив

2023-07-30 18:49 UTC, YAKUDZA1312 commented on src/partials/rent.html
> +          <use href="../img/rent.img/symbol-defs.svg#arrow"></use>
Додав