rename img box
ultra-marina/project-july2023 pull request #31
Opened 2023-08-01 11:24 UTC by OlexandrJ

переіменува папку с зображеннями

2023-08-01 18:29 UTC, ultra-marina requested changes

2023-08-02 09:10 UTC, ultra-marina requested changes

2023-08-02 09:10 UTC, ultra-marina commented on src/css/services.css
Давай зупинимося на тому, що:
mobile: до 767.8px (якщо треба вказувати верхню межу)
tablet: з 768px до 1279.8px (якщо треба вказувати верхню межу)
desktop: починаючи з 1280px
Щоб вони не пересікалися в різних медіа-запитах.

2023-08-02 16:10 UTC, ultra-marina requested changes
Соррі, схоже, я забула повторити своє прохання, коли писала коментар про перестановку в перших і останніх рядках:
Секції потрібний клас section, а її дів-контейнеру - клас container, тому що в загальних стилях написано:
.section {
  padding-bottom: 80px;
}
@media only screen and (min-width: 768px) {
  .section {
    padding-bottom: 100px;
  }
}
@media only screen and (min-width: 1280px) {
  .section {
    padding-bottom: 164px;
  }
}

.container {
  min-width: 320px;
  max-width: 375px;
  margin-right: auto;
  margin-left: auto;
  padding-right: 20px;
  padding-left: 20px;
}
@media only screen and (min-width: 768px) {
  .container {
    max-width: 768px;
    padding-right: 32px;
    padding-left: 32px;
  }
}
@media only screen and (min-width: 1280px) {
  .container {
    max-width: 1280px;
  }
}
Тобто ані секції, ані контейнеру це не треба прописувати повторно.
Виправ, будь ласка, зараз.
Дякую!

2023-08-02 17:43 UTC, OlexandrJ commented
зробив

2023-08-02 17:44 UTC, ultra-marina approved these changes

2023-08-02 17:44 UTC, merged