Update about.css
ultra-marina/project-july2023 pull request #54
Opened 2023-08-03 19:34 UTC by Darjetii-Dooku

2023-08-03 20:11 UTC, ultra-marina requested changes

2023-08-03 20:11 UTC, ultra-marina commented on src/css/about.css
> +    max-width: 183px;
Там в одного 183, в іншого 185. Не знаю, що краще написати. 184? 185?

2023-08-03 20:11 UTC, ultra-marina commented on src/css/about.css
> +  margin-bottom: 40px;
А на планшеті та десктопі - 64?

2023-08-03 20:31 UTC, Darjetii-Dooku commented on src/css/about.css
> +    max-width: 183px;
неважливо, текст обох елементів відповідає макету.

2023-08-03 20:36 UTC, Darjetii-Dooku commented on src/css/about.css
> +  margin-bottom: 40px;
відредагував

2023-08-04 13:28 UTC, ultra-marina approved these changes

2023-08-04 13:28 UTC, merged